# update 25.02.2026
# Shadowrocket Setup (проксируются только заблокированные домены) 
# Repo: vasyakin/shadowrocket-rules

[General]
bypass-system = true
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true

# DNS: Использование DoH для защиты от подмены DNS провайдером
dns-direct-system = false
dns-fallback-system = true
dns-direct-fallback-proxy = false
dns-server = https://dns.google/dns-query, https://cloudflare-dns.com/dns-query
fallback-dns-server = system

# Перехват DNS на порту 53 необходим для корректной работы RULE-SET
hijack-dns = 8.8.8.8:53, 8.8.4.4:53, 1.1.1.1:53

# Расширенный список исключений для локальной инфраструктуры
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com, mtalk.google.com

icmp-auto-reply = true
always-real-ip = *.srv.nintendo.net, xbox.*.microsoft.com, *.xboxlive.com
udp-policy-not-supported-behaviour = DIRECT

[Rule]
# 1. REJECT (Блокируем мусор до того, как он пойдет в прокси)
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/block/ads.list,REJECT

# 2. PROXY SERVICES (тут все, что блокируется в России)
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/telegram.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/youtube.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/x_twitter.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/instagram.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/discord.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/whatsapp.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/viber.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/gemini.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/formula1.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@refs/heads/main/rules/proxy/blocked_russia.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/spotify.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/streaming.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/soundcloud.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@main/rules/proxy/mixcloud.list,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/vasyakin/shadowrocket-rules@refs/heads/main/rules/proxy/ai.list,PROXY

# 3. GEOIP (каитайские домены и ip из бызы GeoLite2)
GEOIP,CN,DIRECT

# Всё, что не попадает под вышеуказанные правила, обрабатывается напрямую
FINAL,DIRECT

