[General]
bypass-system = true
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true

# DNS: DoH
dns-direct-system = false
dns-fallback-system = false
dns-direct-fallback-proxy = false
dns-server = https://dns.google/dns-query, https://cloudflare-dns.com/dns-query
fallback-dns-server = https://dns.quad9.net/dns-query

skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,169.254.0.0/16,localhost,*.local,captive.apple.com,mtalk.google.com

# Battery/stability
icmp-auto-reply = false

always-real-ip = time.apple.com, time.cloudflare.com
udp-policy-not-supported-behaviour = DIRECT

[Rule]
# 1) LOCAL & SYSTEM
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/lan.list,DIRECT

# 2) REJECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/block/ads.list,REJECT

# 3) DIRECT SERVICES
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/apple_domains.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/apple_useragent.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/apple_ip.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/ru_services.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/ru.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/duolingo.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/google_direct.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/china_direct.list,DIRECT

# 4) PROXY (спец-сервисы)
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/proxy/apple_music.list,PROXY

# 5) GEOIP fallback
#GEOIP,RU,DIRECT

# 6) Default
FINAL,PROXY
