#Update 03.03.2026
[General]
bypass-system = true
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true

# DNS: DoH
dns-direct-system = false
dns-fallback-system = false
dns-direct-fallback-proxy = true
dns-server = https://dns.google/dns-query, https://cloudflare-dns.com/dns-query
fallback-dns-server = https://dns.quad9.net/dns-query

# Hijack DNS (force DNS through SR)
hijack-dns = :53

skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,169.254.0.0/16,localhost,*.local,captive.apple.com,mtalk.google.com

# Battery/stability
icmp-auto-reply = false

# Return real IP only for time sync endpoints
always-real-ip = time.apple.com, time.cloudflare.com

# If proxy policy doesn't support UDP, send UDP direct instead of rejecting
udp-policy-not-supported-behaviour = DIRECT


#[Proxy Group]
# Auto-test fastest node among policies that match regex (usually all proxies)
# interval: seconds; timeout: seconds
# AUTO = url-test,interval=600,timeout=5,url=https://cp.cloudflare.com/generate_204,policy-regex-filter=.*

[Rule]
# 1) LOCAL & SYSTEM
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/lan.list,DIRECT

# 2) REJECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/block/ads.list,REJECT

# 3) DIRECT SERVICES
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/apple_domains.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/apple_useragent.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/apple_ip.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/ru_services.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/ru.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/duolingo.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/google_direct.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/direct/china_direct.list,DIRECT

# 4) PROXY (спец-сервисы)
# RULE-SET,https://cdn.jsdelivr.net/gh/MyNicknme/shadowrocket-rules@main/rules/proxy/apple_music.list,PROXY

# 5) GEOIP fallback (optional)
GEOIP,RU,DIRECT

# 6) Default
FINAL,PROXY
